config/routes.rb
CroceviaSantacroce::Application.routes.draw do
  
  match "/patate", to: "patate#index"

  resources :photos, :path => "/galleria"
  
  resources :codice_fiscale, only: [:create]

  resources :messages do
  end
  
  resources :conversations, :path => "/messaggi", only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
      post :mark_as_read
      post :mark_as_unread
    end
  end
  
  
  match 'documenti/:year/:month/:day' => 'documenti#index',
    :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/ },
    :as => 'lista_documenti'

  resources :documenti

  match '/cassa',   controller: 'cassa', action: 'index'
  match '/stats',   controller: 'cassa', action: 'stats'
  
  
  match 'movimenti/:year/:month/:day' => 'movimenti#index',
      :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/ },
      :as => 'lista_movimenti'

  resources :movimenti
  
  resources :categorie

  resources :articoli do
    get 'pagina/:page', :action => :index, :on => :collection
    # collection { post :search, to: 'articoli#index' }
    collection do
      put :etichette, format: :pdf
    end
  end

  resources :clienti do
    member do
      get :mandato
      get :tessera
      get :situazione
      get :crea_codice_fiscale
    end
    get 'pagina/:page', :action => :index, :on => :collection
  end

  authenticated :user do
    root :to => 'home#welcome'
  end
  root :to => "home#index"
  
  
  # ho dovuto cambiare nell initializer delete to get per il logout funziona ma non e corretto
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  
  resources :users, :only => [:show, :index, :update]


  match '/regolamento', to: 'home#regolamento'
  match '/staff',       to: 'home#staff'
  match '/dove_siamo',  to: 'home#dove_siamo'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @photos = Photo.disponibili
  end
  
  def regolamento
  end
  
  def staff
  end
  
  def dove_siamo
  end
  
  def welcome
    @photos = Photo.disponibili
  end
end

app/views/home/dove_siamo.html.haml
= content_for :head do
  = javascript_include_tag "http://maps.google.com/maps/api/js?sensor=true"
  = javascript_include_tag "/javascripts/gmaps.js"

%section.dove_siamo.span6
  .map-container
    #map-home
  %br
  %address
    %h2 Crocevia snc
    %p
      via Santa Croce 11/abcde
      %br
      40121 Bologna
      %br
      %span
        %i.icon-phone
        051 64.90.677
      %br
      %span
        %i.icon-envelope
        = mail_to "mercatino@crocevia-santacroce.com"


:javascript
  $(document).ready( function() {
    
    if ($('#map-home').length > 0) { 
      console.log('urra');
      var map = new GMaps({
        div: '#map-home',
        scrollwheel: false,
        lat: 44.49857200306232,
        lng: 11.332459900305139
      });
      
      map.drawRoute({
        origin: [44.50249184009872, 11.33302944445802],
        destination: [44.496153, 11.329235],
        travelMode: 'drive',
        strokeColor: 'blue',
        strokeOpacity: 0.6,
        strokeWeight: 6      
      });


      map.drawRoute({
        origin: [44.49927790307992, 11.327107126953138],
        destination: [44.496153, 11.329235],
        travelMode: 'drive',
        strokeColor: 'red',
        strokeOpacity: 0.6,
        strokeWeight: 6      
      })


      map.drawRoute({
        origin: [44.49897180459999, 11.327965433837903],
        destination: [44.496153, 11.329235],
        travelMode: 'driving',
        strokeColor: 'green',
        strokeOpacity: 0.6,
        strokeWeight: 6
      });

      map.addMarker({
        lat: 44.496153,
        lng: 11.329235,
        color: 'blue',
        title: "Crocevia - mercato dell'usato",
        infoWindow: {
          content: "<p><strong>Crocevia - mercato dell'usato</strong></br>Via Santa Croce 11/abcde</br>40122 Bologna</p>"         
        }
      });
       
    };
  
  
  });
  

app/views/home/index.html.haml
= content_for :left_col do
  &nbsp

.span12  
  .hero-unit
    %h1 
      il mercato
      %br
      dell'usato 
      %br 
      in centro 
      %br
      a Bologna
      %small con parcheggio privato
    %br  
    %p.lead
      Porta in conto vendita quello che non usi: l'esposizione è gratuita e alla vendita ricevi un rimborso, in contanti, dal 50 al 65% del prezzo.
      %a.btn.btn-danger{ href: "https://maps.google.com/maps?q=via+santa+croce+bologna" }
        %i.icon-truck
        Mappa
    %p
      Siamo a tua disposizione per valutare gratuitamente mobili e oggetti ingombranti a domicilio.
      %a.btn.btn-primary{ href: "tel:+390516490677" }
        %i.icon-phone
        051 64.90.677

  / .hero-unit
  /   %p.lead
  /     i nostri artisti...

  /   #ettore{ style: "width: 580px; margin: auto"}
  /     = image_tag asset_path('events/ettore_si_mostra.png')

  / .hero-unit
  /   %p.lead
  /     e i nostri oggetti...  

  /   = render 'photos/mosaic'

  

app/views/home/regolamento.html.haml
%section.regolamento.well.span6

  .pull-right
    = link_to "#", class: "btn btn-stampami", onclick: "window.print();return false;" do
      %i.icon-print
      Stampami

  %h3
    REGOLE
    %small per il venditore
  
  %ol
    %li
      CROCEVIA mercato dell'usato svolge un' attività di intermediazione nella compravendita fra privati.
    %li
      Per poter vendere occorre essere identificati tramite documento valido e registrati alla prima accettazione di merce e ad ogni scadenza del documento.
    %li
      La tessera rilasciata al venditore è necessaria per mettere in vendita la merce nel nostro mercato ed ha funzione di riconoscimento di proprietà della stessa. La tessera andrà esibita al momento della riscossione dei crediti.
    %li Le spese di smontaggio e trasporto degli articoli da esporre al mercato sono a carico del venditore.
    %li
      Gli oggetti in vendita saranno esposti gratuitamente per 
      %strong 60 giorni al prezzo concordato.
    %li
      %strong Allo scadere dei primi 60 giorni, il prezzo della merce sarà automaticamente scontato del 50%.
    %li
      %strong Il venditore rimane proprietario della merce presente sulla sua lista di carico per 90 giorni.
      Durante questo periodo di tempo il venditore ha la possibilità di poter riprendere possesso in qualsiasi momento degli oggetti lasciati in conto vendita presso il mercato Crocevia di Via Santa Croce.
    %li
      %strong Trascorsi 90 giorni di deposito della merce, il venditore perde ogni diritto sulla merce se è rimasta invenduta e mai ritirata personalmente.
    %li
      %strong A discrezione del Mercato Crocevia, la merce scaduta da più di 90 giorni verrà smaltita, donata in beneficenza oppure venduta a miglior prezzo di realizzo.
    %li
      Il ricavato della vendita della merce sarà a disposizione del venditore dal
      %strong 1° giorno lavorativo del mese successivo a quello di vendita e per 12 mesi
      , trascorsi i quali il rimborso non sarà più possibile e senza che il venditore abbia più nulla a pretendere.
    %li
      %strong È compito del venditore informarsi sul venduto e sulle scadenze della propria merce.
    %li
      È anche compito del venditore ritirare la merce qualora non voglia farla scadere o lasciarla andare in beneficenza. In tal caso dovrà essere lo stesso venditore ad essere capace di reperire la propria merce all'interno del mercatino.
    %li
      La riscossione del ricavato dovrà essere effettuata dal venditore stesso o da un suo incaricato munito di delega e fotocopia del documento del venditore.
    %li
      %strong Si accettano in vendita solo oggetti funzionanti, in buono stato di conservazione e puliti.
    %li
      Gli articoli di elettronica, informatica, elettrodomestici e tutto ciò che non può essere testato a fondo per comprovarne il perfetto funzionamento, vengono venduti con una settimana di garanzia.
    %li
      Qualora non constatato al momento dell'accettazione,
      %strong gli oggetti guasti, resi o fallati verranno in un secondo momento rimossi dalla vendita e tenuti in giacenza per 30 giorni in zona accettazione. Sarà compito del venditore informarsi dello stato dei suoi resi e richiederne il possesso. Eventuali spese di trasporto saranno a suo carico.
    %li
      %strong Trascorsi 30 giorni di giacenza gli oggetti resi e non reclamati dal legittimo proprietario verranno smaltiti oppure donati in beneficenza senza alcun preavviso.
    %li
      La valutazione di mobili, arredamenti completi e articoli di grandi dimensioni o difficili da trasportare può essere effettuata gratuitamente a domicilio previo accordo con i titolari del mercato o per mezzo di fotografie.
    %li
      Il venditore solleva da qualunque responsabilità il mercato e i suoi titolari in caso di furto, incendio, danneggiamenti parziali o totali per cause dolose o accidentali o colpose anche da parte di terzi agli articoli lasciati in deposito nei locali del mercato.
    %li
      %strong La provvigione trattenuta dal mercatino sul prezzo di vendita di tutti gli articoli è pari al 50%, tranne per i mobili di valore superiore ai 200 euro, che sarà del 35%.

  %h3
    REGOLE
    %small per l'acquirente
  
  %ol
    %li
      All'acquirente può essere richiesta l'identificazione tramite presentazione di un documento e la registrazione con tesseramento come tutela contro l'incauto acquisto.
    %li
      Le spese di trasporto e montaggio degli articoli acquistati sono a carico dell'acquirente.
    %li
      Gli articoli possono essere riservati dietro versamento di una caparra pari ad almeno il 30% del prezzo di vendita e per un tempo non superiore ai 7 giorni, termine dopo il quale l'acquirente perde la caparra e l'oggetto può essere rimesso in vendita.

    %li
      Garanzia: gli articoli elettrici ed elettronici acquistati che una volta messi in funzione presentino evidenti difetti, rotture, malfunzionamenti non dichiarati dal venditore, possono essere cambiati
      %strong entro e non oltre una settimana
      portando come prova d'acquisto, l'etichetta adesiva originale con prezzo e codice.


    
  

app/views/home/staff.html.haml
%section.staff.span6
  %header
    %h2 Il nostro staff
    %article.member.clearfix
      = link_to image_tag( asset_path('bert.jpg'), size: "160x160" ), ""
      %h3 Marzia Bertoncelli
      %p
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

    %article.member.clearfix
      = link_to image_tag( asset_path('bert.jpg'), size: "160x160" ), ""
      %h3 Stefano Scifoni
      %p
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  
  
    %article.member.clearfix
      = link_to image_tag( asset_path('bert.jpg'), size: "160x160" ), ""
      %h3 Elena Belletti
      %p
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  
      
    %article.member.clearfix
      = link_to image_tag( asset_path('tax.jpg'), size: "160x160" ), ""
      %h3 @paolotax
      %p
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/home/upload_photo.html.haml
= content_for :left_col do
  &nbsp


.span12  
  = render 'photos/load_photos'

app/views/home/welcome.html.haml
= content_for :left_col do
  &nbsp

.span12
  .hero-unit
    %h1= sexize_string("Benvenuto, ", "Benvenuta, ", current_user.name.split(" ")[0]) + current_user.name
    %p
      ti ringraziamo per esserti iscritto.
      %br
      Al momento non ci sono servizi disponibili
    %p 
      Entra nella
      = link_to photos_path, class: 'btn btn-warning' do
        %i.icon-picture
        Galleria
      per vedere alcune delle nostre proposte. 

  / .hero-unit
  /   %p.lead
  /     i nostri artisti...

  /   #ettore{ style: "width: 580px; margin: auto"}
  /     = image_tag asset_path('events/ettore_si_mostra.png')

  / .hero-unit
  /   %p.lead
  /     e i nostri oggetti...  

  /   = render 'photos/mosaic'