config/routes.rb
CroceviaSantacroce::Application.routes.draw do
  
  match "/patate", to: "patate#index"

  resources :photos, :path => "/galleria"
  
  resources :codice_fiscale, only: [:create]

  resources :messages do
  end
  
  resources :conversations, :path => "/messaggi", only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
      post :mark_as_read
      post :mark_as_unread
    end
  end
  
  
  match 'documenti/:year/:month/:day' => 'documenti#index',
    :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/ },
    :as => 'lista_documenti'

  resources :documenti

  match '/cassa',   controller: 'cassa', action: 'index'
  match '/stats',   controller: 'cassa', action: 'stats'
  
  
  match 'movimenti/:year/:month/:day' => 'movimenti#index',
      :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/ },
      :as => 'lista_movimenti'

  resources :movimenti
  
  resources :categorie

  resources :articoli do
    get 'pagina/:page', :action => :index, :on => :collection
    # collection { post :search, to: 'articoli#index' }
    collection do
      put :etichette, format: :pdf
    end
  end

  resources :clienti do
    member do
      get :mandato
      get :tessera
      get :situazione
      get :crea_codice_fiscale
    end
    get 'pagina/:page', :action => :index, :on => :collection
  end

  authenticated :user do
    root :to => 'home#welcome'
  end
  root :to => "home#index"
  
  
  # ho dovuto cambiare nell initializer delete to get per il logout funziona ma non e corretto
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  
  resources :users, :only => [:show, :index, :update]


  match '/regolamento', to: 'home#regolamento'
  match '/staff',       to: 'home#staff'
  match '/dove_siamo',  to: 'home#dove_siamo'
end

app/controllers/clienti_controller.rb
class ClientiController < ApplicationController
  
  load_and_authorize_resource
  
  def index
    @q = Cliente.order("id desc").search(params[:q])
    @clienti = @q.result(distinct: true).pagina(params[:page]).per(25)

    @gino = @clienti.count
  end
  
  def show
    @cliente = Cliente.includes(:articoli).find(params[:id])
    
    if request.path != cliente_path(@cliente)
      redirect_to @cliente, status: :moved_permanently
    end
  end
  
  def new
  end  

  def create
    if @cliente.save
      redirect_to clienti_path, notice: "Cliente inserito con successo!"
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @cliente.update_attributes(params[:cliente])
      redirect_to @cliente, notice: "Cliente modificato."
    else
      render :edit
    end
  end
  
  def destroy
    @cliente.destroy
    redirect_to clienti_path, notice: "Cliente eliminato!."
  end
  
  def mandato
  end
  
  def tessera
    @cliente.to_barby
    respond_to do |format|
      format.pdf do
        pdf = TesseraPdf.new(@cliente, view_context)
        send_data pdf.render, filename: "tessera_#{@cliente.id}_#{@cliente.full_name}_#{Time.zone.now}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end
  
  def situazione
    respond_to do |format|
      format.pdf do
        pdf = SituazioneClientePdf.new(@cliente, view_context)
        send_data pdf.render, filename: "situazione_#{@cliente.id}_#{Time.zone.now}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end
  
  def crea_codice_fiscale
    @codice_fiscale = CodiceFiscale.new(@cliente)
    render json: @codice_fiscale.to_json
  end
  
end

app/views/clienti/_articoli_attivi.html.haml
%section.articoli-attivi.clearfix
  = render "articoli/form"

  .clearfix    
  %br  

  .empty-rows{class: "#{'hidden' if @cliente.has_articoli_attivi? }"}
    Non ci sono articoli da caricare    

  %table#articoli-da-caricare.table.articoli      
    %tr.table-header{ class: "#{'hidden' unless @cliente.has_articoli_attivi? }" }
      / %th.barcode Barcode
      %th.codice      Codice
      %th.articolo    Articolo
      %th.pezzi       Quantità
      %th.prezzo      Prezzo
      %th.provvigione Provvigione
      %th
      %th
     
    - for articolo in @cliente.articoli.attivo do
      - unless articolo.new_record?
        = render articolo
  
    %tr.table-footer{ class: "#{'hidden' unless @cliente.has_articoli_attivi? }"}
      %td{ colspan: 2} Totale
      %td.pezzi
        %strong= @cliente.articoli.attivo.sum(&:giacenza) 
      %td.prezzo
        %strong= number_to_currency @cliente.articoli.attivo.sum(&:importo), locale: :it
      %td.provvigione
        %strong= number_to_currency @cliente.articoli.attivo.sum(&:importo_provvigione), locale: :it
      %td.actions
        = form_tag etichette_articoli_path, :method => :put, :id => "form_articoli", class: "pull-right", target: "_blank" do
          - for a in @cliente.articoli.attivo do
            = hidden_field_tag "articolo_ids[]", a.id unless a.new_record?
          = hidden_field_tag "tipo_etichetta", "Dymo 11352"
          = submit_tag "Etichette",  id: "bt-pdf", class: "btn"
      %td.actions
        = form_for Documento.new, html: {class: "pull-right"} do |f|
          = hidden_field_tag "cliente_id", @cliente.id
          = f.hidden_field :data,       value: Time.now
          = f.hidden_field :tipo,       value: "carico"
          = f.submit "registra", class: "btn btn-success"
      

app/views/clienti/_attenzione_cassa.html.haml
- unless cliente.vendite.attivo.empty?
  = link_to cassa_path, class: "attenzione_cassa" do
    .alert.alert-error
      %h4
        Attenzione!
      = pluralize( cliente.vendite.attivo.size, "articolo" )
      da incassare. Clicca per andare alla Cassa 

app/views/clienti/_attenzione_resa.html.haml
- unless cliente.rese.attivo.empty?
  .attenzione-resa
    = form_for Documento.new, html: {class: "pull-right"} do |f|
      = hidden_field_tag "cliente_id", cliente.id
      = f.hidden_field :data,       value: Time.now
      = f.hidden_field :tipo,       value: "resa"
      = f.submit "Registra Resa", class: "btn btn-danger"
    %h4
      Attenzione!
    

    = render 'movimenti/movimenti_list',  collection: cliente.rese.attivo,    label: "articolo_reso_da_registrare"

app/views/clienti/_attenzione_rimborso.html.haml
- unless cliente.vendite.non_eli.rimborsabile.empty?
  .attenzione-rimborso
    = form_for Documento.new, html: {class: "pull-right"} do |f|
      = hidden_field_tag "cliente_id", cliente.id
      = f.hidden_field :data,       value: Time.now
      = f.hidden_field :tipo,       value: "rimborso"
      = f.submit "Rimborsa", class: "btn btn-warning"

    %h4
      Attenzione!
    / = pluralize( cliente.vendite.non_eli.rimborsabile.size, "articolo" )
    / = number_to_currency( cliente.vendite.non_eli.rimborsabile.sum(&:importo_provvigione), locale: :it)
    / da rimborsare.

    = render 'movimenti/movimenti_list',  collection: cliente.vendite.non_eli.rimborsabile, label: "articolo_da_rimborsare"
      
      

app/views/clienti/_cliente.html.haml
%tr[cliente]
  %td= cliente.id
  %td= link_to cliente.full_name, cliente
  %td
    %small= cliente.created_at.strftime("%d-%m-%y")
  %td.rimborsi
    = "#{number_to_currency(cliente.vendite.rimborsabile.sum(&:importo_provvigione), locale: :it) if cliente.has_vendite_da_rimborsare?}"

app/views/clienti/_clienti_header.html.haml
%thead.clienti
  %tr
    %th.codice
      = sort_link @q, :id, "codice"
    %th.full_name
      = sort_link @q, :nome, "cliente"
    %th.created_at
      = sort_link @q, :created_at, "caricato il"

app/views/clienti/_form.html.haml
= content_for :left_col, class: "falsa-colonna" do
  &nbsp
  
= simple_form_for @cliente, :html => { :class => 'form-horizontal'} do |f|
  .row
    .span12
      = f.error_notification
      .row
        .span6
          %fieldset.dati-anagrafici
            %legend Dati anagrafici
            = f.input :nome
            = f.input :cognome
            = f.input   :sesso, collection: [["maschio", "m"], ["femmina", "f"]], prompt: "scegli il sesso"
            = f.input   :data_di_nascita_text, label: "Data di nascita", input_html: { class: "datepicker" }
            = f.input   :comune_di_nascita, html5: true
            
            = f.input :codice_fiscale, wrapper: :append, hint: "#{'clicca la mano per calcolare il codice fiscale'}" do
              = f.input_field :codice_fiscale, class: :mini
              / - unless @cliente.new_record?
              = content_tag :span, class: "add-on get-cf btn"  do
                %i.icon-hand-left 

            = f.input   :partita_iva
            = f.input   :ragione_sociale
            
        .span6
          %fieldset
            %legend Documento d'identità
            = f.input :tipo_documento, collection: ["carta d'identità", "patente", "passaporto"]
            = f.input :numero_documento
            = f.input :documento_rilasciato_da, label: "Rilasciato da"
            = f.input :data_rilascio_documento_text, label: "Data rilascio", input_html: { class: "datepicker" }

      .row
        .span6
          %fieldset
            %legend Indirizzo
            = f.input :indirizzo
            = f.input :cap
            = f.input :citta
            = f.input :provincia
        .span6
          %fieldset
            %legend Recapiti & note
            = f.input :telefono
            = f.input :cellulare
            = f.input :email
            = f.input :note,  :input_html => { :rows => 2 }
      
      = f.error :base
      
      .form-actions
        = f.button :submit, :class => 'btn btn-primary'
        = link_to "Annulla", @cliente, :class => 'btn btn-danger'

app/views/clienti/edit.html.haml
= render 'form'

app/views/clienti/index.html.haml
= content_for :left_col do
  .span3.side-bar
    %ul.nav.nav-list.well
      %li.nav-header
        %i.icon-user
        Clienti
      %li
        = link_to new_cliente_url do
          %i.icon-plus
          Nuovo
      %li
        = link_to clienti_url do
          %i.icon-user
          tutti
      %li.divider
    

      = search_form_for @q, html: {class: "form-search", style: "margin-bottom: 0"} do |f|
        .input-append
          = f.text_field :index_cont, class: "search-query", placeholder: "cerca cliente", style: "width: 110px"
          = button_tag class: "btn", name: nil do
            %i.icon-search

.span9
  .page-header
    %h1 Clienti
  %table.table
    = render "clienti_header"
    %tbody.clienti
      - for cliente in @clienti do
        = render cliente
  
  = paginate @clienti, remote: false

app/views/clienti/index.js.erb
$('thead.clienti').replaceWith("<%= escape_javascript render('clienti_header') %>");

$('tbody.clienti').html('<%= escape_javascript render(@clienti) %>');

$('nav.pagination').html('<%= escape_javascript(paginate(@clienti, :remote => true).to_s) %>');

app/views/clienti/index_bak.js.erb
$('thead.clienti').replaceWith("<%= escape_javascript render('clienti_header') %>");

$('tbody.clienti').html('<%= escape_javascript render(@clienti) %>');

$('nav.pagination').html('<%= escape_javascript(paginate(@clienti, :remote => true).to_s) %>');

app/views/clienti/mandato.html.haml
.pull-right
  = link_to "#", class: "btn btn-stampami", onclick: "window.print();return false;" do
    %i.icon-print
    Stampami

.mandato
  %p.dati-ditta.hidden
    di Marzia Bertoncelli s Stefano Scifoni snc Via Santa Croce 11/abcde - 40121 BOLOGNA Tel e Fax 051.64.90.677
    %br
    Email: mercatino@crocevia-santacroce.com Web: crocevia-santacroce.com - P.IVA 03218281206

  .intestazione
    %h4 
      = "MANDATO DI VENDITA N. #{@cliente.id - 2 } del #{@cliente.created_at.strftime('%d/%m/%Y')}"
      %small da Mandante n.
      %strong= @cliente.id
    %p
      - if @cliente.maschio?
        Io sottoscritto
      - else
        Io sottoscritta
        
      %strong= @cliente.cognome_nome.upcase
      mandante in qualità di cliente privato
      %br
      
      - if @cliente.maschio?
        nato il
      - else
        nata il
        
      = "#{@cliente.data_di_nascita_text }"
      = "a #{@cliente.comune_di_nascita}"
      = "Cod.Fisc. #{@cliente.codice_fiscale}"
      
      %br
      residente in:
      = @cliente.indirizzo
      = @cliente.cap
      = @cliente.citta
      = @cliente.provincia  
      %br
      = "Documento: #{@cliente.tipo_documento.upcase} N. #{@cliente.numero_documento} ril/rin. il #{@cliente.data_rilascio_documento_text} Da: #{@cliente.documento_rilasciato_da}"
      
  
  %p.testo-mandato
    Dò mandato di vendita a nome e per mio conto degli oggetti di mia proprietà come da allegata "lista oggetti ricevuti" alla ditta sopra citata, di seguito denominata Mandatario, alle seguenti condizioni e per n∞ 90 giorni di esposizione:

    %ol
      %li Gli oggetti restano di mia proprietà fino alla loro vendita e permangono presso il Mandatario in  esposizione gratuita salvo quanto esposto di seguito.
      %li Prendo atto che mi verrà corrisposto dopo la vendita l'importo ricavato meno la percentuale di provvigione IVA compresa concordata come specificato nella "lista oggetti ricevuti".

      %li Prendo atto che l'importo degli oggetti venduti detratta la provvigione di cui al punto 2 mi sarà messo a disposizione a partire dal primo giorno del mese successivo alla vendita dei singoli oggetti consegnati in vendita. Fino alla data della riscossione il Mandatario sarà custode per mio conto dell'importo stesso e le spese sostenute dallo stesso per la custodia delle somme incassate in nome e per mio conto si intendono compensate con i frutti eventualmente percepiti in dipendenza del deposito, in deroga agli art. 1775/1781 Cod.Civ.

      %li Prendo atto che ogni diritto di riscossione dei crediti relativi agli oggetti venduti in nome e per mio conto decade trascorso un anno dalla vendita degli stessi (art. 2964 Cod. Civ).

      %li Prendo atto che la durata massima dell' esposizione è di 60 gg. e che dopo tale termine gli oggetti invenduti e non ritirati potranno essere scontati dal Mandatario fino ad un massimo del 50% del prezzo concordato per ulteriori 30 giorni.

      %li Prendo atto che, scaduti i termini del contratto (90 gg.) senza nessun preavviso da ambo le parti, autorizzo il Mandatario a determinare il prezzo di vendita al maggior realizzo.

      %li Prendo atto che, al fine di evitare lo sconto come da punto 5 e la determinazione dei prezzi da parte del Mandatario come da punto 6 sarà esclusivamente mia cura aggiornarmi sui tempi di esposizione ed eventualmente provvedere al ritiro della merce; in deroga all'art.1712 del Codice Civile sollevo il Mandatario dall'obbligo di comunicare l'esecuzione del Mandato di vendita.

      %li Sono consapevole che, ai fini dell'esecuzione del mandato, i dati personali da me conferiti saranno trattati con l'ausilio di strumenti elettronici dal Mandatario, nel rispetto degli artt. 13 e 7 del D.Lgs. 196/2003 ("Codice in materia di protezione dei dati personali") di cui ho preso visione.
  %br
  .firme    
    %p Firma Mandante  ___________________
    %br
    %p per esplicita approvazione dei punti 3.4.5.6.7.8.
    %br
    %p Firma Mandante  ___________________

app/views/clienti/new.html.haml
= render 'form'

app/views/clienti/show.html.haml
= content_for :left_col do
  .span3.side-bar
    %ul.nav.nav-list.well
      %li.nav-header
        %i.icon-user
        Clienti
      %li
        = link_to new_cliente_url do
          %i.icon-plus
          Nuovo
      %li
        = link_to edit_cliente_url(@cliente) do
          %i.icon-pencil
          Modifica
      %li
        = link_to clienti_url do
          %i.icon-user
          tutti
      %li.divider
      %li
        = link_to mandato_cliente_url(@cliente) do
          %i.icon-print
          Stampa mandato
      %li
        = link_to tessera_cliente_url(@cliente, format: 'pdf'), target: "_blank" do
          %i.icon-tag
          Stampa tessera    
      %li
        = link_to situazione_cliente_url(@cliente, format: 'pdf'), target: "_blank" do
          %i.icon-money
          Stampa situazione    

.span9
  
  %h3= @cliente.full_name

  %address
    = @cliente.indirizzo
    %br
    = "#{@cliente.cap} #{@cliente.citta} #{@cliente.provincia}"

  .dati-fiscali
    = @cliente.codice_fiscale
    = @cliente.partita_iva

  .info_documento
    = @cliente.tipo_documento
    = "num. #{@cliente.numero_documento}"
    = "rilasciato da: #{@cliente.documento_rilasciato_da}"
    = "il #{@cliente.data_rilascio_documento.try(:strftime, "%d-%m-%y")}"
  
  %br
  = render 'articoli_attivi'
  %br


  .articoli-venduti
    = render 'attenzione_cassa', cliente: @cliente
    = render 'attenzione_rimborso', cliente: @cliente
    
    = render 'movimenti/movimenti_list',  collection: @cliente.vendite.non_eli.select{|m| !m.da_rimborsare? && !m.rimborsato? && !m.attivo?}, label: "articolo_venduto"

  = render 'attenzione_resa', cliente: @cliente
  
  
  .articoli-in-giacenza
    = render 'articoli/articoli_list', label: "articolo_in_giacenza", collection: @cliente.articoli.registrato.disponibili.non_eli.order("articoli.documento_id desc, articoli.id")
  


  - unless @cliente.rimborsi.empty?  && @cliente.resi.empty? 
    .articoli-storici
      %h4 Rimborsi & Rese
      %table.table.articoli-rimborsati
        = render (@cliente.rimborsi + @cliente.resi).sort {|a, b| b.id <=> a.id}
    