config/routes.rb
CroceviaSantacroce::Application.routes.draw do
  
  match "/patate", to: "patate#index"

  resources :photos, :path => "/galleria"
  
  resources :codice_fiscale, only: [:create]

  resources :messages do
  end
  
  resources :conversations, :path => "/messaggi", only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
      post :mark_as_read
      post :mark_as_unread
    end
  end
  
  
  match 'documenti/:year/:month/:day' => 'documenti#index',
    :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/ },
    :as => 'lista_documenti'

  resources :documenti

  match '/cassa',   controller: 'cassa', action: 'index'
  match '/stats',   controller: 'cassa', action: 'stats'
  
  
  match 'movimenti/:year/:month/:day' => 'movimenti#index',
      :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/ },
      :as => 'lista_movimenti'

  resources :movimenti
  
  resources :categorie

  resources :articoli do
    get 'pagina/:page', :action => :index, :on => :collection
    # collection { post :search, to: 'articoli#index' }
    collection do
      put :etichette, format: :pdf
    end
  end

  resources :clienti do
    member do
      get :mandato
      get :tessera
      get :situazione
      get :crea_codice_fiscale
    end
    get 'pagina/:page', :action => :index, :on => :collection
  end

  authenticated :user do
    root :to => 'home#welcome'
  end
  root :to => "home#index"
  
  
  # ho dovuto cambiare nell initializer delete to get per il logout funziona ma non e corretto
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  
  resources :users, :only => [:show, :index, :update]


  match '/regolamento', to: 'home#regolamento'
  match '/staff',       to: 'home#staff'
  match '/dove_siamo',  to: 'home#dove_siamo'
end

app/controllers/articoli_controller.rb
require "prawn/measurement_extensions"

class ArticoliController < ApplicationController
  
  load_and_authorize_resource

  def index
    @q = Articolo.includes(:cliente).joins(:cliente).order("articoli.id desc").search(params[:q])
    @articoli = @q.result(:distinct => true).pagina(params[:page]).per(30)
  end
 
  def create
    @articolo = Articolo.create(params[:articolo])
    
    respond_to do |format|
      format.html { redirect_to @articolo.cliente }
      format.js
    end
  end
  
  def destroy
    @articolo.destroy
    respond_to do |format|
      format.html { redirect_to @articolo.cliente }
      format.js
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @articolo.update_attributes(params[:articolo])
      redirect_to @articolo, notice: "Articolo modificato."
    else
      render :edit
    end
  end
  
  def etichette
    @articoli = Articolo.order(:id).find(params[:articolo_ids])
    
    respond_to do |format|
      format.pdf do
        
        case params[:tipo_etichetta]
          when "Dymo 11352"
            options = {
              page_size:  [25.mm, 54.mm],
              labels_per_page: 1,
              columns: 1
            }
        end  

        pdf = EtichettaPdf.new(@articoli, view_context, options)
        send_data pdf.render, filename: "etichette_#{Time.now}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end    
end

app/helpers/articoli_helper.rb
module ArticoliHelper

  def table_articoli(collection, name='', options={})
    content_tag :table, class: "table #{name}" do
      render collection
    end  
  end

end

app/views/articoli/_articoli_header.html.haml
%thead.articoli
  %tr
    %th.id
      = sort_link @q, :id, "codice"
    %th.articolo
      = sort_link @q, :nome, "articolo"
    %th.quantita
      quantita
    %th.prezzo
      = sort_link @q, :prezzo, "prezzo"
    %th.provvigione
      provv.
    / %th.created_at
    /   = sort_link @q, :created_at, "caricato il"
    / %th.venditore
    /   = sort_link @q, :cliente_nome, "cliente"

app/views/articoli/_articoli_list.haml
%section{ class: "#{label}" }
  %header
    %h3 
      = pluralize( collection.size, label )
      %small= link_to "...", "##{label}", class: "show-hide collapsed", data: { toggle: "collapse", "no-turbolink" => true }

  %div.collapse{ id: "#{label}" }
    %table.table.articoli      
      %tr.table-header{ class: "#{'hidden' if collection.empty? }" }
        %th.codice Codice
        %th.articolo Articolo
        %th.prezzo Prezzo
        %th.provvigione Provvigione
        %th
      
      - for articolo in collection do
        = render 'movimenti/movimento', movimento: articolo

      %tr.table-footer{ class: "#{'hidden' if collection.empty? }"}
        %td{ colspan: 2} Totale
        %td.quantita
          %strong= collection.sum(&:quantita) 
        %td.prezzo
          %strong= number_to_currency collection.sum(&:importo)
        %td.provvigione
          %strong= number_to_currency collection.sum(&:importo_cliente)
        %td.actions{ colspan: 2}

app/views/articoli/_articoli_list.html.haml
%section{ class: "#{label}" }
  %header
    %h4 
      = pluralize( collection.sum(&:giacenza), label.humanize.downcase )
      - if collection.size > 0
        %small= link_to "...", "##{label}", class: "show-hide", data: { toggle: "collapse", "no-turbolink" => true }

  %div.collapse.in{ id: "#{label}" } 
    %table.table.articoli  
      %tr.table-header{ class: "#{'hidden' if collection.empty? }" }
        %th.codice      Codice
        %th.articolo    Articolo
        %th.pezzi    Quantità
        %th.prezzo      Prezzo
        %th.provvigione Provvigione
        %th
        %th
        %th
        %th
    
      - collection.group_by(&:documento).each do |key, values|
        %tr
          %td
            %small 
              = link_to key.mandante, key.mandante
          %td{ colspan: 7 }
            = link_to "Carico N." + key.id.to_s + " del " + key.data.strftime("%d/%m/%Y"), key

          %td
            = link_to 'x', key, class: "close", method: :delete, confirm: "Elimino il documento?\n(i movimenti non verranno eliminati)", "data-no-turbolink" => false
            
        = render values

      %tr.table-footer{ class: "#{'hidden'  if collection.empty? }"}
        %td{ colspan: 2} Totale
        %td.pezzi
          %strong= collection.sum(&:giacenza) 
        %td.prezzo
          %strong= number_to_currency collection.sum(&:importo), locale: :it
        %td.provvigione
          %strong= number_to_currency collection.sum(&:importo_provvigione), locale: :it
        %td.actions{ colspan: 4 }

app/views/articoli/_articolo.html.haml
%tr[articolo]
  %td.id= link_to "art.#{articolo.id}", articolo
  %td.nome= articolo.nome

  %td.quantita= articolo.quantita
  %td.giacenza= articolo.giacenza
  %td.prezzo= number_to_currency articolo.prezzo, locale: :it
  %td.provvigione= number_to_percentage articolo.categoria.provvigione, precision: 0
  
  %td
    - if articolo.patate?
      .label.label-info.pull-left
        patate #{articolo.giorni_di_giacenza}
    - elsif articolo.scaduto?
      .label.label-warning.pull-left
        scaduto #{articolo.giorni_di_giacenza}  
    - else
      scade tra #{articolo.categoria.scadenza - articolo.giorni_di_giacenza} giorni


  - unless articolo.attivo?
    %td.etichetta.actions-mini
      = form_tag etichette_articoli_path, :method => :put, :id => "form_articoli", class: "pull-right", target: "_blank" do
        = hidden_field_tag "articolo_ids[]", articolo.id
        = hidden_field_tag "tipo_etichetta", "Dymo 11352"
        = button_tag id: "bt-pdf", class: "btn btn-mini" do
          %i.icon-tag
          eti
    %td.rendi.actions-mini
      - if articolo.disponibile?
        = form_for Movimento.new, remote: false do |f|
          = f.hidden_field :articolo_id, value: articolo.id
          = f.hidden_field :tipo, value: "resa"
          = f.submit  "Rendi", class: "btn btn-danger btn-mini pull-right" 
    %td.vendi.actions-mini
      - if articolo.disponibile?    
        = form_for Movimento.new, remote: false do |f|
          = f.hidden_field :articolo_id, value: articolo.id
          = f.hidden_field :tipo, value: "vendita"
          = f.submit  "Vendi", class: "btn btn-success btn-mini pull-right" 
  - else
    %td{ colspan: 2}
      = link_to articolo, method: :delete, class: "close", remote: false, "data-no-turbolink" => false do
        &times;

app/views/articoli/_form.html.haml
= form_for @cliente.articoli.build, class: "form-inline", remote: true do |f|

  = f.hidden_field :cliente_id


  .input-prepend.provvigione.pull-left
    %span.add-on cat
    = f.collection_select :categoria_id, Categoria.all, :id, :nome, { selected: Articolo.last.categoria_id.to_i}, {placeholder: "provvigione", required: true} 
  
  .pull-left
    = f.text_field :nome, placeholder: "articolo", required: true

  .input-prepend.prezzo.pull-left
    %span.add-on €
    = f.text_field :prezzo, class: 'span1', step: :any, min: 0, placeholder: "prezzo", required: true
  

  .input-prepend.quantita.pull-left
    %span.add-on Pz.
    = f.number_field :quantita, class: 'span1', value: 1, min: 1, placeholder: "pezzi", required: true

  
  
  .pull-right
    = f.submit "Aggiungi", class: "btn btn-primary"
  

app/views/articoli/_history.html.haml
%section.history

  - if @articolo.documento
    = link_to @articolo.documento do
      .alert.alert-info
        %strong
          Caricato il
          = l @articolo.documento.data, format: :default
        con documento nr  
        = @articolo.documento.id
  - else
    = link_to @articolo.cliente do
      .alert.alert-error
        %h4
          Attenzione!
        carico da registrare. Clicca per registrare il carico del cliente

  - unless @articolo.movimenti.vendita.empty?
    - for m in @articolo.movimenti.vendita do
      - if m.documento
        - if m.rimborsato?
          = link_to m.rimborso do
            .alert
              %span
                %strong
                  Rimborso del
                = l m.rimborso.data, format: :default
                cassa nr.
                = m.rimborso.id 
              %span.pull-right
                %strong
                  = number_to_currency m.prezzo, locale: :it
        - else
          = link_to m.documento do
            .alert.alert-success
              %span
                %strong
                  Venduto il
                = l m.documento.data, format: :default
                cassa nr.
                = m.documento.id 
              %span.pull-right
                %strong
                  = number_to_currency m.prezzo, locale: :it
      - else
        = link_to cassa_path do
          .alert.alert-error
            %h4
              Attenzione!
            vendita da incassare. Clicca per registrare il movimento di cassa
        
  - unless @articolo.movimenti.resa.empty?
    - for m in @articolo.movimenti.resa do
      - if m.documento
        = link_to m.documento do
          .alert
            %span
              %strong
                Reso il
              = l m.documento.data, format: :default
              resa nr.
              = m.documento.id 
      - else
        = link_to @articolo.cliente do
          .alert.alert-error
            %h4
              Attenzione!
            resa da registrare. Clicca per registrare la resa del cliente

app/views/articoli/create.js.erb
$("#articoli-da-caricare .table-footer").before("<%= escape_javascript(render @articolo) %>");

$("input#articolo_nome").val("");
$("input#articolo_prezzo").val("")
$("input#articolo_quantita").val(1)

$("input#articolo_nome").focus();

$("#articoli-da-caricare .table-footer .quantita strong").html("<%= @articolo.cliente.articoli.attivo.attivo.sum(&:giacenza)  %>")
$("#articoli-da-caricare .table-footer .prezzo strong").html("<%= number_to_currency @articolo.cliente.articoli.attivo.sum(&:importo), locale: :it %>")
$("#articoli-da-caricare .table-footer .provvigione strong").html("<%= number_to_currency @articolo.cliente.articoli.attivo.sum(&:importo_provvigione), locale: :it %>")


$("#articoli-da-caricare .table-header").removeClass("hidden")
$("#articoli-da-caricare .table-footer").removeClass("hidden")
$(".empty-rows").addClass("hidden")

$("#form_articoli").append("<input type='hidden' name='articolo_ids[]' value='<%= @articolo.id %>'/>")

app/views/articoli/destroy.js.erb
$("#<%=  dom_id(@articolo) %>").remove();

$("#articoli-da-caricare .table-footer .quantita strong").html("<%= @articolo.cliente.articoli.attivo.sum(&:giacenza)  %>")
$("#articoli-da-caricare .table-footer .prezzo strong").html("<%= number_to_currency @articolo.cliente.articoli.attivo.sum(&:importo), locale: :it %>")
$("#articoli-da-caricare .table-footer .provvigione strong").html("<%= number_to_currency @articolo.cliente.articoli.sum(&:importo_provvigione), locale: :it %>")

if ($("#articoli-da-caricare .articolo").length == 1) {
  $("#articoli-da-caricare .table-header").addClass("hidden");
  $("#articoli-da-caricare .table-footer").addClass("hidden");
  $(".empty-rows").removeClass("hidden");
}

$("input[value='<%= @articolo.id %>']").remove();

app/views/articoli/edit.html.haml
= simple_form_for @articolo, :html => { :class => 'form-horizontal' } do |f|
  
  = f.error_notification
  
  %fieldset
    %legend 
      Modifica Articolo
      %small di
      %small
        = link_to @articolo.cliente.full_name, @articolo.cliente

  
    = f.input :nome, placeholder: "articolo", label: "Articolo", :input_html => { class: "input-xlarge", required: true, autofocus: true }
  
    = f.input :prezzo, placeholder: "prezzo", :input_html => { class: "input-mini", required: true, step: :any, min: 0 }
    / .input-prepend.prezzo.pull-left
    /   %span.add-on €
    /   = f.number_field :prezzo, class: 'input-mini',  placeholder: "prezzo", required: true
  
    = f.input :quantita, placeholder: "quantita", :input_html => { class: "input-mini", required: true, value: 1, min: 1 }

    / %span.add-on %
    = f.input :provvigione, placeholder: "provvigione", collection: ["50", "65"], :input_html => { class: 'input-mini', value: 50 , required: true }
  
  = f.error :base
  
  .form-actions
    = f.submit "Salva Modifiche", :class => 'btn btn-primary'
    

app/views/articoli/index.html.haml
= content_for :left_col do
  .span3.side-bar
    %ul.nav.nav-list.well
      %li.nav-header
        %i.icon-gift
        Articoli
        
      %li
        = link_to articoli_url, remote: true do
          %i.icon-gift
          tutti
      %li.divider
      
      = search_form_for @q,  html: {class: "form-search", style: "margin-bottom: 0"} do |f|
        .input-append
          = f.text_field :index_cont, class: "search-query", placeholder: "cerca articolo", style: "width: 110px"
          = button_tag class: "btn", name: nil do
            %i.icon-search
              
.span9
  .page-header
    %h1 Articoli 
  %table.table
    = render "articoli_header"
    = render @articoli 
  = paginate @articoli

app/views/articoli/index.js.erb
$('thead.articoli').replaceWith("<%= escape_javascript render('articoli_header') %>");

$('tbody.articoli').html('<%= escape_javascript render(@articoli) %>');

$('nav.pagination').html('<%= escape_javascript(paginate(@articoli, :remote => true).to_s) %>');

app/views/articoli/show.html.haml
= content_for :left_col do
  .span3.side-bar
    %ul.nav.nav-list.well
      %li.nav-header
        %i.icon-user
        Articoli
      %li
        = link_to edit_articolo_url(@articolo) do
          %i.icon-pencil
          Modifica
      %li
        = link_to @articolo, method: :delete, confirm: "Sei sicuro?" do
          %i.icon-trash
          Elimina

      %li
        = link_to articoli_url do
          %i.icon-user
          tutti
      
      %li.divider

      %li.nav-header
        %i.icon-gift
        Articoli
      
      %li
        = link_to articoli_url do
          %i.icon-gift
          tutti

%section.span9
  
  .page-header
    - if @articolo.disponibile?
      .pull-right
        = form_tag etichette_articoli_path, :method => :put, :id => "form_articoli", class: "btn-articolo", target: "_blank" do
          = hidden_field_tag "articolo_ids[]", @articolo.id
          = hidden_field_tag "tipo_etichetta", "Dymo 11352"
          = button_tag id: "bt-pdf", class: "btn" do
            %i.icon-tag
            eti
        = form_for Movimento.new, html: { class: "btn-articolo"} do |f|
          = f.hidden_field :articolo_id, value: @articolo.id
          = f.hidden_field :tipo, value: "resa"
          = f.submit  "Rendi", class: "btn btn-danger"
        = form_for Movimento.new, html: { class: "btn-articolo"} do |f|
          = f.hidden_field :articolo_id, value: @articolo.id
          = f.hidden_field :tipo, value: "vendita"
          = f.submit  "Vendi", class: "btn btn-success" 

    %h3
      = @articolo.nome
      %small
        di
        = link_to @articolo.cliente.full_name, @articolo.cliente
  .row
    .span5
      %p
        codice articolo: #{@articolo.id.to_s}
        %br
        quantità: #{@articolo.quantita}
        %br
        prezzo: #{number_to_currency @articolo.prezzo, locale: :it}
        %br
        provvigione: #{number_to_percentage @articolo.provvigione, precision: 0}
        %br
        giacenza: #{@articolo.giacenza}
        %br
        data carico: #{l @articolo.data_carico, format: :default}
        %br
        data scadenza: #{l @articolo.data_scadenza, format: :default}

      = render "history"
      

    %section.galleria_articolo.span4  
      %ul#foto_articolo.thumbnails
        = render @articolo.photos  
        %li.dropzone.span2
          .inner
            trascina qui una
            o più fotografie
            %br
            = form_for Photo.new, html: { "data-no-turbolink" => true } do |f|
              = f.hidden_field :articolo_id, value: @articolo.id
              = f.file_field :photo, multiple: true, name: "photo[photo]", class: "hidden"



%script{ id: "template-upload", type: "text/x-tmpl"}
  .upload
    / {%= o.name %}
    .progress
      .bar{ style: "width: 0%"}