config/routes.rb
CroceviaSantacroce::Application.routes.draw do
  
  match "/patate", to: "patate#index"

  resources :photos, :path => "/galleria"
  
  resources :codice_fiscale, only: [:create]

  resources :messages do
  end
  
  resources :conversations, :path => "/messaggi", only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
      post :mark_as_read
      post :mark_as_unread
    end
  end
  
  
  match 'documenti/:year/:month/:day' => 'documenti#index',
    :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/ },
    :as => 'lista_documenti'

  resources :documenti

  match '/cassa',   controller: 'cassa', action: 'index'
  match '/stats',   controller: 'cassa', action: 'stats'
  
  
  match 'movimenti/:year/:month/:day' => 'movimenti#index',
      :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/ },
      :as => 'lista_movimenti'

  resources :movimenti
  
  resources :categorie

  resources :articoli do
    get 'pagina/:page', :action => :index, :on => :collection
    # collection { post :search, to: 'articoli#index' }
    collection do
      put :etichette, format: :pdf
    end
  end

  resources :clienti do
    member do
      get :mandato
      get :tessera
      get :situazione
      get :crea_codice_fiscale
    end
    get 'pagina/:page', :action => :index, :on => :collection
  end

  authenticated :user do
    root :to => 'home#welcome'
  end
  root :to => "home#index"
  
  
  # ho dovuto cambiare nell initializer delete to get per il logout funziona ma non e corretto
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  
  resources :users, :only => [:show, :index, :update]


  match '/regolamento', to: 'home#regolamento'
  match '/staff',       to: 'home#staff'
  match '/dove_siamo',  to: 'home#dove_siamo'
end

app/views/layouts/_link_cassa.html.haml
- if can? :manage, Movimento
  %li.cassa
    = link_to cassa_path do
      = badge_if current_user.movimenti.vendita.attivo.length, class: "badge-important pull-right", style: "margin: -15px -25px -25px 0"
      %i.icon-shopping-cart.icon-large
      Cassa

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-static
  .navbar-inner
    .container
      = link_to image_tag('crocevia232x81.png'), root_path, :class => 'brand'
      %ul.nav.actions    
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{ href: '#', "data-toggle" => 'dropdown'}
              = current_user.name
              = badge_if current_user.mailbox.inbox.unread(current_user).length, class: "badge-important pull-right", style: "margin: -15px -25px -25px 0"
              %b.caret

            %ul.dropdown-menu
              %li= link_to('il mio profilo', edit_user_registration_path)
              %li.divider
              %li
                = link_to( "messaggi", :conversations)
              %li= link_to( "nuovo messaggio", :new_conversation)
              %li.divider  
              %li
                = link_to "Esci", destroy_user_session_path, id: "sign_out", :method=>'delete', "data-no-turbolink" => true 
        - else
          %li
            = link_to "Accedi con Facebook", user_omniauth_authorize_path(:facebook), id: "sign_in", "data-no-turbolink" => true
          %li
            = link_to "Accedi", new_user_session_path
          %li
            = link_to('Iscriviti!', new_user_registration_path)

        - if user_signed_in? 
          - if current_user.has_role? :admin
            %li
              = link_to_unless_current users_path do
                = link_to "Utenti", users_path
        
        - if can? :manage, Documento
          %li.dropdown
            %a.dropdown-toggle{ href: '#', "data-toggle" => 'dropdown' }
              Magazzino
              %b.caret
            %ul.dropdown-menu
              %li= link_to "venduto", stats_path
              %li.divider
              %li= link_to "tutti i documenti", documenti_path
              %li= link_to "tutti i movimenti", movimenti_path

        - if can? :manage, Cliente
          %li.dropdown
            %a.dropdown-toggle{ href: '#', "data-toggle" => 'dropdown'}
              Clienti
              = badge_if Articolo.attivo.pluck(:cliente_id).uniq.size, class: "badge-important pull-right", style: "margin: -15px -25px -25px 0"
              
              %b.caret
            %ul.dropdown-menu
              %li= link_to "tutti i clienti", clienti_path
              %li= link_to "nuovo cliente",  new_cliente_path
              %li.divider
              %li
                = form_tag clienti_path, name: "clienti_search", id: 'clienti_search', method: 'get'  do
                  = text_field_tag "q[index_cont]", nil, class: "search-query", placeholder: "cerca clienti", style: "margin: 0 10px -10px 10px"
                  
        - if can? :manage, Articolo
          %li.dropdown
            %a.dropdown-toggle{ href: '#', "data-toggle" => 'dropdown' }
              Articoli
              %b.caret
            %ul.dropdown-menu
              %li= link_to "tutti gli articoli", articoli_path
              %li.divider
              %li
                = form_tag articoli_path, name: "articoli_search", id: 'articoli_search', method: 'get'  do
                  = text_field_tag "q[index_cont]", nil, class: "search-query", placeholder: "cerca articoli", style: "margin: 0 10px -10px 10px"
        
        = render 'layouts/link_cassa'
             

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Crocevia - Mercato dell'usato"
    %meta{:content => "Il mercatino dell'usato in centro a Bologna", :name => "description"}
    %meta{:content => "mercatino, usato, mercato, bologna, crocevia, santacroce, santa, croce, pratello, thrift, shop, vintage, usati", :name => "keywords"}

    %meta{:content => "@paolotax", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body{ class: "#{controller.controller_name} #{controller.action_name}"}
    #loading
      %strong caricamento....
      
    %header
      = render 'layouts/navigation'
      
    .container
      = render 'layouts/messages'
      .row
        %div{ class: content_for?(:left_col) ? "span12" : "span6 offset3"}
          .row
            = yield :left_col
            = yield

    %footer
      .navbar
        .navbar-inner
          .container
            %ul.nav.actions
              %li 
                = link_to_unless_current "Home", root_path do
                  &nbsp
              %li 
                = link_to_unless_current "Regolamento", regolamento_path do
                  &nbsp
              / %li  
              /   = link_to_unless_current "Staff", staff_path do
              /     &nbsp
              %li  
                = link_to_unless_current "Dove siamo?", dove_siamo_path, "data-no-turbolink" => true do
                  &nbsp